# Generated by Django 4.2 on 2023-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('show', models.BooleanField(default=True)),
                ('view_count', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
