# Generated by Django 4.2 on 2023-04-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_image_article_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('company', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('expire', models.DateField()),
                ('lang', models.BooleanField()),
            ],
        ),
    ]
